# Generated by Django 4.1 on 2024-03-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='items/', verbose_name='Image')),
                ('amount', models.IntegerField(default=0, verbose_name='Amount')),
                ('price', models.IntegerField(default=0, verbose_name='Price-$')),
                ('added_time', models.DateTimeField(auto_now_add=True, verbose_name='Date&Time')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
    ]
